import { Hooks } from './../../code/model/hooks';
import { Plugin, PluginFramework } from '../../code/model/plugin';
import { minify } from 'html-minifier';

export default class HtmlMinifierPlugin extends Plugin {
    constructor(wyver: PluginFramework) {
        super(wyver);
        wyver.hooks.set('builder:generate#after', (source: string)=> {
            return this.minify(source);
        });
    }

    minify(source: string) {
        const minsrc = <string>minify(source, {
            collapseBooleanAttributes: true,
            collapseInlineTagWhitespace: true,
            collapseWhitespace: true,
            conservativeCollapse: true,
            decodeEntities: true,
            html5: true,
            includeAutoGeneratedTags: true,
            keepClosingSlash: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeRedundantAttributes: true,
            removeScriptTypeAttributes: true,
            removeStyleLinkTypeAttributes: true,
            useShortDoctype: true
        });
        //console.log(source.length, minsrc.length, Math.round(minsrc.length/source.length*100));
        return minsrc;
    }
}
